Shop show
5xRuby13thMarche/Marche pull request #165
Opened 2023-05-19 06:03 UTC by charlie51417

https://github.com/5xRuby13thMarche/Marche/assets/127653623/5d4d4b62-b94f-4c1e-a370-4e985c3d698c

建立賣家專專屬商店頁面
左側邊欄可以找出所有商品的子分類篩選
上方邊欄可以選擇最新 價格最高 價格最低排序

目前紅框標題範圍尚未加資料 ：logo 商店資訊 賣出總數 等等

2023-05-19 07:54 UTC, matsuyama2000 approved these changes

2023-05-19 10:24 UTC, kevinlee629 commented
現在左側的分類項目會重複
<img width="924" alt="截圖 2023-05-19 下午6 24 06" src="https://github.com/5xRuby13thMarche/Marche/assets/130286574/57454ecb-4e45-4085-ae66-53b0c36dfc9d">

2023-05-19 16:48 UTC, Hsuan19971005 requested changes

2023-05-19 16:48 UTC, Hsuan19971005 commented on app/views/shops/_category_list.html.erb
> +  <% @sub_categories.each do |content| %>
這邊的@sub_categories應該要由外面傳參數進來

2023-05-19 16:48 UTC, Hsuan19971005 commented on app/controllers/shops_controller.rb
這邊的商品圖片會有N+1問題吧

2023-05-20 10:02 UTC, kevinlee629 approved these changes

2023-05-21 05:15 UTC, Hsuan19971005 approved these changes

2023-05-21 05:46 UTC, merged