Issues/13
5xRuby13thMarche/Marche pull request #168
Opened 2023-05-19 10:39 UTC by kg936512

#12 交易成功醒目
<img width="1440" alt="RWD交易完成按鈕" src="https://github.com/5xRuby13thMarche/Marche/assets/127717275/9402500c-c01e-40b7-83eb-6b7714d6a4bc">

#13 訂單頁面查看所有的button會爆版(手機版)
<img width="1440" alt="訂單成立頁面按鈕爆開" src="https://github.com/5xRuby13thMarche/Marche/assets/127717275/47838392-6db7-42ed-9127-69303a24e165">

#16 收件人資訊的表單太醜，inputs沒對齊（手機版）
<img width="1440" alt="結帳頁面欄位對齊" src="https://github.com/5xRuby13thMarche/Marche/assets/127717275/cef2d752-1106-431f-8e68-79aaf8749799">

#25 訂單成立頁面字太多會超出畫面（手機版）
<img width="1440" alt="訂單成立頁面資訊過多爆版" src="https://github.com/5xRuby13thMarche/Marche/assets/127717275/763bb1b3-8a89-491c-a677-803f99f9c243">

#33 #33 訂單頁面的訂單如果沒有付款成功，要可以再付一次
<img width="1440" alt="結帳失敗重新購買" src="https://github.com/5xRuby13thMarche/Marche/assets/127717275/46a62f73-64d6-41c6-862b-26e2bbc94ee4">

#34 訂單產生後的頁面也要有大的Navbar
<img width="1440" alt="訂單成立頁面有navbar" src="https://github.com/5xRuby13thMarche/Marche/assets/127717275/46ca3775-58f9-42cd-a463-96cd2512674b">

swiper目前做到一半，怕ＰＲ太大包，所以先發

2023-05-19 17:06 UTC, Hsuan19971005 requested changes
1. 資料庫欄位資訊應該繼續使用：pending, paid，但是「畫面上」要翻譯成中文
2. commit訊息有些錯誤，可以使用 rebase -i 進行改寫，包含："Optimize前面多了 " ，Adjusting應該改成 Adjust

2023-05-19 17:06 UTC, hsiaoyihsuan commented on app/assets/stylesheets/application.css
這裡應該要改成在application.tailwind.css對每個class做設定，非不得已不要寫在這裡。

2023-05-19 17:06 UTC, hsiaoyihsuan commented on app/assets/stylesheets/application.css
> +body {
這裡對body做樣式的設定很奇怪，這樣會導致全站所有body都套用這樣的設定，為了商品照片而影響全站不太好。

2023-05-19 17:06 UTC, hsiaoyihsuan commented on app/controllers/orders_controller.rb
> +      @order.update(payment_status: "付款成功" )
在資料庫中，payment_status的設定目前看起來是只有：
- pending
- paid

應該是都用統一的英文，之前任務中所描述的「全站的pending、paid 改成中文」，意思是指「畫面」中的pending、paid改成「已付款」、「尚未付款」之類的中文，但是資料庫中的格式依然要是統一的英文才對。

2023-05-19 17:06 UTC, hsiaoyihsuan commented on app/controllers/orders_controller.rb
> +
order.rb中有寫一個方法叫generate_tracking_number，經過code review後，這種複雜的行為就不要再controller中做了。

2023-05-19 17:06 UTC, hsiaoyihsuan commented on app/views/layouts/application.html.erb
> +
其實可以把這個改寫成stimulus，如果你有時間的話。

2023-05-19 17:06 UTC, Hsuan19971005 commented on app/views/orders/paid.html.erb
> +<%= render 'shared/for_paid' if flash.any? %>
這個partial template的名稱不太好，可以簡單的叫_paid就好，將介系詞當作開頭很奇怪。

2023-05-19 17:06 UTC, Hsuan19971005 commented on app/views/orders/paid.html.erb
> +  <% if @order.payment_status != "付款成功" %>
這邊就是資料庫欄位變成中文，很奇怪，照理來說要寫成：
`@order.payment_status == 'pending'`

2023-05-19 17:06 UTC, Hsuan19971005 commented on app/views/shared/_for_paid.html.erb
partial render的名稱改成 「_paid.html.erb」

2023-05-21 05:06 UTC, kg936512 commented on app/controllers/orders_controller.rb
> +      @order.update(payment_status: "付款成功" )
已改回

2023-05-21 06:03 UTC, kg936512 commented on app/assets/stylesheets/application.css
已修改

2023-05-21 09:00 UTC, matsuyama2000 approved these changes

2023-05-21 10:26 UTC, charlie51417 approved these changes

2023-05-22 06:54 UTC, Hsuan19971005 approved these changes

2023-05-22 06:55 UTC, merged