新增 購物流程資料到cart_products&new頁面新增分類選擇& 建立seed假資料產生
5xRuby13thMarche/Marche pull request #45
Opened 2023-04-25 12:51 UTC by charlie51417

#14 
新建與修改之功能：
1. 建立分類與商品假資料seed檔
2.new頁面新增分類
3.建立購買流程並將商品資料傳到cart
4.改變category與product資料庫關聯

功能說明：
1. 建立分類與商品假資料seed檔
`rails db:seed`
分類：產生5筆主分類與5筆次分類
商品：產生10筆隨機商品

2.商品new頁面（目前做到顯示主分類與非主分類）
<img width="1277" alt="截圖 2023-04-25 下午7 29 18" src="https://user-images.githubusercontent.com/127653623/234263424-ee733e61-fff6-4965-ac13-a34ad8f25ed4.png">

3.建立購買流程並將商品資料傳到cart

- 點選商品輸入數量，選擇`加入購物車`，轉到購物車頁面並顯示商品名稱規格
- cart路徑目前僅新增 index & create

目前購買流程為商品顯示頁面(show)塞入一個form，輸入quantity後，點選`加入購物車`
<img width="675" alt="截圖 2023-04-27 下午5 27 34" src="https://user-images.githubusercontent.com/127653623/234821104-657dcd6c-a8a5-4988-8e2c-90ef07a93e15.png">
表單會將一個帶有cart_product前綴的hash{ 內含sale_info_id與quantity }丟給cart controller處理，在cart_controller中將指定這包資料指向目前使用者的購物車，最後顯示在cart頁面中(cart/index)
<img width="1280" alt="截圖 2023-04-27 下午5 30 36" src="https://user-images.githubusercontent.com/127653623/234821580-7b967b1b-8d2d-4c04-9f7f-afef8ad9e8f6.png">

4.改變category與product資料庫關聯=>多對多 改為 一對多

未完成功能：
1. 建立分類與商品假資料seed檔

- seed中商品尚未建立主分類與次分類機制，目前為隨機賦予一個category_id

2. new頁面

- category清單之關聯選取功能待處理
- validates待處理
- 切版

3. 建立購買流程並將商品資料傳到cart

- 商品顯示頁面尚未建立庫存與數量機制（ex.數量選擇不能超過庫存，庫存為零時不能購買）
- quantity須在後端做限制（不能傳送不正確資訊）
- cart_controller 當save後如果失敗需顯示資訊（待處理）
- 購物車之規格需有下拉選單
- 購物車改變規格後能改變其購買資訊
- 購物車修改刪除

4. 商品show頁面

- 切版
- 返回主頁與編輯按鈕待修改

2023-04-25 13:02 UTC, kevinlee629 approved these changes

2023-04-25 15:49 UTC, matsuyama2000 approved these changes

2023-04-26 04:01 UTC, sharondolly approved these changes

2023-04-26 07:40 UTC, kevinlee629 approved these changes

2023-04-26 08:52 UTC, Hsuan19971005 requested changes
我覺得這包PR太大包，應該可以拆成很多個PR來審，至少先拆成4包：分類功能、新增產品功能、購物車功能、產品畫面設計

2023-04-26 08:52 UTC, hsiaoyihsuan commented on db/migrate/20230423123850_change_column_default_to_cart_products.rb
> +    change_column_default :cart_products, :quantity, 0
cart_products的quantity，不是已經預設是 default: 0了嗎？
在20230419131910_create_cart_products.rb中有寫

2023-04-26 08:52 UTC, hsiaoyihsuan commented on app/views/products/show.html.erb
> +          <%= form_with(model: CartProduct.new, url: cart_products_path, method: :post, data: { turbo: false }) do |form| %>
view裡面最好不要寫CartProduct.new，這應該是Controller做的事情。

2023-04-26 08:52 UTC, hsiaoyihsuan commented on app/javascript/controllers/quantity_controller.js
> +    this.valueTarget.value++;
increase跟decrease的寫法不一致，一個有parseInt，一個沒有。

2023-04-26 08:52 UTC, hsiaoyihsuan commented on app/views/products/_form.html.erb
> +        <%= c.collection_select(:id, Category.where("parent_id > ?", 0), :id, :content, { prompt: "請選擇" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2") %>
這邊在view做了Category.where，這個工作應該要在Controller中執行，或是在view helper中執行。

2023-04-26 08:52 UTC, hsiaoyihsuan commented on app/views/categories/index.html.erb
> +<% @categories.each do |c|%>
用迴圈render頁面不太適合，應該寫一個partial render collection

2023-04-26 08:52 UTC, hsiaoyihsuan commented on app/models/product.rb
> +  accepts_nested_attributes_for :sale_infos
可以說明一下accepts_newsted_attributes_for在這邊的作用嗎？

2023-04-26 08:52 UTC, Hsuan19971005 commented on app/models/product.rb
> +  belongs_to :categories, optional: true
belongs_to 後面要接單數

2023-04-26 08:52 UTC, Hsuan19971005 commented on app/javascript/controllers/index.js
@zhanjian0217 助教～ 你可以看一下這個檔案嗎？我不確定這樣會不會壞掉。

2023-04-26 08:52 UTC, Hsuan19971005 commented on app/controllers/cart_products_controller.rb
> +    @cart_product = current_user.cart.cart_products.new(cart_product_params)
從sale_info的角度new一個新的cart_product就可以簡化這一行，不然這樣串燒式的寫法很難閱讀。

2023-04-26 08:52 UTC, Hsuan19971005 commented on app/controllers/products_controller.rb
> +      @product
這邊有一個落單的@product

2023-04-26 08:52 UTC, Hsuan19971005 commented on app/controllers/products_controller.rb
> +      params.require(:product).permit(:name, :description, sale_infos_attributes: [:id, :price], category_ids: [])
可以說明一下這個寫法嗎？

2023-04-26 08:52 UTC, Hsuan19971005 commented on app/controllers/products_controller.rb
> +    @product.sale_infos.build
這邊很奇怪，build一個sale_info，但卻沒有存。

2023-04-26 13:51 UTC, kg936512 approved these changes

2023-04-26 14:46 UTC, kevinlee629 approved these changes

2023-04-26 15:28 UTC, zhanjian0217 commented on app/javascript/controllers/index.js
>  application.register("product--like", Product__LikeController)
這邊要刪掉，因為你用了新的引入方式

2023-04-26 15:28 UTC, zhanjian0217 commented on app/models/product.rb
> +  belongs_to :categories, optional: true
```ruby
belongs_to :category, optional: true
```

2023-04-26 15:28 UTC, zhanjian0217 commented on app/models/product.rb
> +  accepts_nested_attributes_for :sale_infos
https://www.google.com/search?q=accepts_newsted_attributes_for&rlz=1C5CHFA_enTW1030TW1030&oq=accepts_newsted_attributes_for&aqs=chrome..69i57j0i13i512l4j0i13i30l5.364j0j7&sourceid=chrome&ie=UTF-8

因為要建立 `product` 時順便建立 `sale_infos` 這個關聯性的 Model，會用到的方法

2023-04-26 15:28 UTC, zhanjian0217 commented on app/models/user.rb
> +  after_create :build_cart
```ruby 
after_create :create_cart
```

2023-04-26 15:28 UTC, zhanjian0217 commented on app/models/user.rb
> +    self.create_cart
這邊就可以刪掉了

2023-04-26 15:28 UTC, zhanjian0217 commented on app/views/categories/index.html.erb
> +<% @categories.each do |c|%>
若是這個頁面真的長這樣的話，那我認為也就不用  `partial render`
再者這個畫面應該不用存在吧

2023-04-26 15:28 UTC, zhanjian0217 commented on app/views/categories/new.html.erb
> +</div>
你有路徑，也有畫面，但是沒有 `Controller`
是不是衝突的時候不小心解掉的

2023-04-26 15:28 UTC, zhanjian0217 commented on app/controllers/products_controller.rb
> +      params.require(:product).permit(:name, :description, sale_infos_attributes: [:id, :price], category_ids: [])
```ruby
params.require(:product).permit(:name, :description, sale_infos_attributes: [:spec, :storage, :price], :category_id)
```

應該要改成這樣，因為你的 `:spec, :storage` 都沒有存進去
關於 `category_id` 只會送出一個，因為你的欄位名稱相同，所以後面會蓋掉前面的
雖然有達到目的，也就是把 `child_category` 送出去

2023-04-26 15:28 UTC, zhanjian0217 commented on app/views/products/_form.html.erb
> +        <%= c.collection_select(:id, Category.where("parent_id > ?", 0), :id, :content, { prompt: "請選擇" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2") %>
若是我會這樣做
```ruby
#products_helper.rb

  def parent_categories
    Category.where(parent_id: nil).pluck(:content, :id)
  end

  def sub_categories
    Category.where.not(parent_id: nil).pluck(:content, :id)
  end
  ```
  ```ruby
  # _form.html.erb
  
<%= form.select :category_id, parent_categories, { prompt: "請選擇" }, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2'  %>
<%= form.select :category_id, sub_categories, { prompt: "請選擇" }, class: 'block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2'  %>
 ```
 
 請看懂為什麼要這樣做，而不是照抄
 然後 `:category_id`重複 的部分我認為應該有更好的解法，就留給你想了

2023-04-26 15:28 UTC, zhanjian0217 commented on app/views/products/show.html.erb
> +          <%= form_with(model: CartProduct.new, url: cart_products_path, method: :post, data: { turbo: false }) do |form| %>
這邊應該連 model 都不用給，因為目的只是加入購物車而已
可以想想為什麼，想不出來再問我

```ruby
<%= form_with url: cart_products_path, method: :post, data: { turbo: false } do |form| %>
```

2023-04-26 15:28 UTC, zhanjian0217 commented on app/views/products/show.html.erb
> +              <%= form.text_field :quantity %>
數量的 input 應該只能填入數字

2023-04-26 15:28 UTC, zhanjian0217 commented on app/views/products/show.html.erb
> +      <%= @product.description %>
```ruby
<%= @product.spec %>
```

2023-04-26 15:28 UTC, zhanjian0217 commented on config/routes.rb
> +  resources :categories, :cart_products
寫成兩行吧，雖然這樣寫很酷
兩行的目的是好維護以及增加新的路徑
而且這兩條 `resources ` 應該不是全部的路徑都需要，請保留需要的就好

```ruby
resources :categories
resources :cart_products
```

2023-04-26 15:28 UTC, zhanjian0217 commented on app/models/cart.rb
>    has_many :cart_products
```ruby 
has_many :cart_products, dependent: :destroy
```

2023-04-26 15:28 UTC, zhanjian0217 commented on app/controllers/carts_controller.rb
> +    @cart = current_user.cart
應該可以 在 application controller 寫一個方法
```ruby
def 購物車 （名字自己想）
    current_user.cart || current_user.create_cart
end

他可以成為 view_helper

2023-04-26 15:28 UTC, zhanjian0217 commented on app/models/product.rb
> +  belongs_to :categories, optional: true
現在 `Product` 的欄位只有這些，應該還需要 `category_id`
["id", "name", "description", "shop_id", "created_at", "updated_at"]

2023-04-26 16:37 UTC, charlie51417 commented on app/javascript/controllers/quantity_controller.js
> +    this.valueTarget.value++;
這個我再修改一下再把它裝到show頁面確保動作正常

2023-04-26 16:37 UTC, charlie51417 commented on app/views/products/show.html.erb
> +          <%= form_with(model: CartProduct.new, url: cart_products_path, method: :post, data: { turbo: false }) do |form| %>
我覺得我有想錯地方了，我需要跟助教釐清一下觀念

2023-04-26 16:37 UTC, charlie51417 commented on db/migrate/20230423123850_change_column_default_to_cart_products.rb
> +    change_column_default :cart_products, :quantity, 0
喔喔有我看到了！我把這個migration刪除

2023-04-26 16:42 UTC, charlie51417 commented on app/views/products/_form.html.erb
> +        <%= c.collection_select(:id, Category.where("parent_id > ?", 0), :id, :content, { prompt: "請選擇" }, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2") %>
感謝助教解答，感覺我資料關聯那邊一直思考錯所以思路有點怪拍寫

2023-04-26 16:43 UTC, charlie51417 commented on app/views/categories/index.html.erb
> +<% @categories.each do |c|%>
對，拍寫我把著個也push上來了這是我拿來測試分類時用的，預計是之後會把分類傳到這建立

2023-04-26 16:54 UTC, charlie51417 commented on app/models/product.rb
> +  accepts_nested_attributes_for :sale_infos
沒錯我的理解是可以在new商品畫面時，同時把sale_info資料也建起來，所以使用fields_for他會在傳送資訊時內嵌一組數據叫`sale_infos_attributes:{}` ，必須是有關聯的model，並在product model輸入上面的`accepts_nested_attributes_for :sale_infos`，所以在permit時候就要把sale_infos_attributes這個hash標示出來

2023-04-26 16:55 UTC, charlie51417 commented on app/models/product.rb
> +  belongs_to :categories, optional: true
有的已修改！

2023-04-26 16:55 UTC, charlie51417 commented on app/controllers/cart_products_controller.rb
> +    @cart_product = current_user.cart.cart_products.new(cart_product_params)
這個我要思考下，剛看了助教的留言覺得好像有些地方想錯了

2023-04-26 16:55 UTC, charlie51417 commented on app/controllers/products_controller.rb
> +      @product
已刪除感謝！

2023-04-26 16:58 UTC, charlie51417 commented on app/controllers/products_controller.rb
> +    @product.sale_infos.build
這個也是內嵌表單的用法
https://rails.ruby.tw/form_helpers.html#%E5%B5%8C%E5%A5%97%E8%A1%A8%E5%96%AE

2023-04-26 16:59 UTC, charlie51417 commented on app/controllers/products_controller.rb
> +      params.require(:product).permit(:name, :description, sale_infos_attributes: [:id, :price], category_ids: [])
上面有提到這個～

我再補上`:spec, :storage` !
有道理`category_id`這個會重複送齁我再想想怎麼改！

2023-04-26 16:59 UTC, charlie51417 commented on app/models/user.rb
> +  after_create :build_cart
收到

2023-04-26 17:00 UTC, charlie51417 commented on app/views/categories/new.html.erb
> +</div>
拍寫我push到這個了這是拿來測試看的

2023-04-26 17:01 UTC, charlie51417 commented on app/views/products/show.html.erb
> +              <%= form.text_field :quantity %>
好！以修改

2023-04-26 17:01 UTC, charlie51417 commented on app/views/products/show.html.erb
> +      <%= @product.description %>
我改成`@sale_info.spec`

2023-04-26 17:05 UTC, charlie51417 commented on app/models/cart.rb
>    has_many :cart_products
已加感謝助教

2023-04-26 17:06 UTC, charlie51417 commented on app/controllers/carts_controller.rb
> +    @cart = current_user.cart
這寫完是否上面的`after_create :creat_cart`就不用加了？

2023-04-27 12:38 UTC, Hsuan19971005 approved these changes

2023-04-27 14:27 UTC, merged