切版＿登入畫面和註冊畫面
5xRuby13thMarche/Marche pull request #55
Opened 2023-04-27 08:58 UTC by sharondolly

![screencapture-localhost-3000-users-sign-up-2023-04-27-16_53_21](https://user-images.githubusercontent.com/130358340/234812671-b5f97413-386c-48e0-b4cf-31ed244cdc6e.png)
![screencapture-localhost-3000-users-sign-in-2023-04-27-16_54_13](https://user-images.githubusercontent.com/130358340/234812752-99bfc819-bec2-4fb3-9d75-39d07339b047.png)
1.註冊畫面和登入畫面切版

2023-04-27 10:11 UTC, charlie51417 commented
如果有沒做完的功能也可以補一下～像是RWD之類不然可能會被擋pr

2023-04-27 10:13 UTC, charlie51417 approved these changes

2023-04-27 10:13 UTC, charlie51417 commented on config/tailwind.config.js
下次有新增css可以在pr說明一下或是放在trellor～到時候大家切版都可以用

2023-04-27 10:24 UTC, matsuyama2000 commented on app/views/devise/sessions/new.html.erb
> +<footer class="footer p-10 bg-marcheblue text-base-content">
我覺得 footer 應該可以用 partial render 的方式

2023-04-27 10:25 UTC, matsuyama2000 commented on app/views/devise/registrations/new.html.erb
> +<footer class="footer p-10 bg-marcheblue text-base-content">
這邊也是

2023-04-27 12:32 UTC, matsuyama2000 commented on app/views/devise/registrations/new.html.erb
> +              <%= f.password_field :password, autocomplete: "new-password" ,class: "rounded-md border-0" ,placeholder: "最少6個字符" %>
請問為什麼把原本的 `@minimum_password_length` 部分刪掉但卻加上最少6個字符的placeholder

```
<% if @minimum_password_length %>
<em>(<%= @minimum_password_length %> characters minimum)</em>
<% end %><br />
<%= f.password_field :password, autocomplete: "new-password", class: 'input' %>
```

2023-04-27 12:59 UTC, matsuyama2000 commented on app/views/devise/sessions/new.html.erb
> +              <%= f.password_field :password, autocomplete: "current-password" ,class: "rounded-md border-0" ,placeholder: "最少6個字符" %>
登入應該不需要提示密碼最少要6個字符，只有註冊時需要

2023-04-28 01:35 UTC, Hsuan19971005 requested changes

2023-04-28 01:35 UTC, hsiaoyihsuan commented on app/assets/stylesheets/form.scss
突然發現我們居然有scss...，這個用taiwind做就好了吧

2023-04-28 01:35 UTC, hsiaoyihsuan commented on app/views/devise/registrations/new.html.erb
> +<br />
這個br怎麼獨自在這沒有縮排

2023-04-28 02:39 UTC, sharondolly commented on app/assets/stylesheets/form.scss
因為用tailwind改不動，所以動了scss

2023-04-28 02:39 UTC, sharondolly commented on app/views/devise/sessions/new.html.erb
> +              <%= f.password_field :password, autocomplete: "current-password" ,class: "rounded-md border-0" ,placeholder: "最少6個字符" %>
收到

2023-04-28 02:43 UTC, sharondolly commented on app/views/devise/registrations/new.html.erb
> +              <%= f.password_field :password, autocomplete: "new-password" ,class: "rounded-md border-0" ,placeholder: "最少6個字符" %>
@minimum_password_length
這行指令會在版面上一直出現(minimumpassword)
我希望他可以顯示中文指示，所以把它刪除。（是不是刪錯東西了QQ)

2023-04-28 02:44 UTC, sharondolly commented on config/tailwind.config.js
收到

2023-04-28 02:46 UTC, sharondolly commented on app/views/devise/sessions/new.html.erb
> +<footer class="footer p-10 bg-marcheblue text-base-content">
摁摁，之後等忠泰的PR過，我會把它改為partial render！

2023-04-28 02:46 UTC, sharondolly commented on app/views/devise/registrations/new.html.erb
> +<br />
我改！

2023-04-28 06:28 UTC, matsuyama2000 commented on app/views/devise/registrations/new.html.erb
> +              <%= f.password_field :password, autocomplete: "new-password" ,class: "rounded-md border-0" ,placeholder: "最少6個字符" %>
了解，對不起是我自己昨天沒有看懂，原本想說可以 `<em>( 至少 <%= @minimum_password_length %> 個字元)</em>` 就好
但你那樣也沒問題！！讚讚

2023-05-05 02:49 UTC, closed without merging