新增商品畫面： 加入規格資訊增加按鈕與刪除按鈕
5xRuby13thMarche/Marche pull request #66
Opened 2023-05-03 02:44 UTC by charlie51417

#14 
1. 修改modal，現在可以點選外部關閉modal
2. 新增sale_info增加與刪除欄位
<img width="1054" alt="截圖 2023-05-03 上午10 40 02" src="https://user-images.githubusercontent.com/127653623/235823417-dd4c4dc5-cbc7-4d31-a41f-52cf6ea656fc.png">

進階說明：
因為sale_info使用的是fields_for嵌入式表單，因此只需透過js新增資訊欄位，傳入後臺後就會被分成多筆sale_info
透過stimulus將範例模板去插入在fields_for表單下藉此渲染畫面

2023-05-03 04:07 UTC, kevinlee629 approved these changes

2023-05-03 05:52 UTC, Hsuan19971005 requested changes
stimulus controller 再修

2023-05-04 09:31 UTC, Hsuan19971005 approved these changes

2023-05-04 09:38 UTC, kg936512 approved these changes

2023-05-05 04:32 UTC, merged