feat: Add amazon s3 bucket for active storage
5xRuby13thMarche/Marche pull request #69
Opened 2023-05-04 09:28 UTC by matsuyama2000

上傳圖片使用 amazon s3 bucket

註冊 > 編輯我的帳戶 > 上傳圖片後可到 rails console 檢查，比如：

```
kk = User.last
kk.avatar.blob
```

s3 的 Access key ID 和 Secret access key 我會放在 trello
可依照範例檔建立 `application.yml`

2023-05-05 01:47 UTC, Hsuan19971005 requested changes
credentials.yml.enc要換成我們原本的，bin/dev才能使用

2023-05-07 04:45 UTC, charlie51417 approved these changes
漂亮

2023-05-07 04:45 UTC, Hsuan19971005 approved these changes

2023-05-07 06:14 UTC, kg936512 approved these changes

2023-05-07 06:14 UTC, merged