Ransack優化搜尋
5xRuby13thMarche/Marche pull request #70
Opened 2023-05-04 10:58 UTC by Hsuan19971005

安裝gem Ransack，優化商品搜尋功能，現在英文大小寫都可以搜尋到商品

2023-05-05 03:46 UTC, kg936512 approved these changes

2023-05-05 06:24 UTC, matsuyama2000 approved these changes

2023-05-06 12:20 UTC, charlie51417 requested changes

2023-05-06 12:20 UTC, charlie51417 commented on app/models/product.rb
> +  def self.ransackable_attributes(auth_object = nil)
想問這個self 是啥用法

2023-05-06 12:20 UTC, charlie51417 commented on app/controllers/products_controller.rb
> +    @q = Product.ransack(params[:q])
要不要考慮換一個名稱哈哈這名稱我實在看不懂

2023-05-06 12:20 UTC, charlie51417 commented on app/views/products/index.html.erb
> +      <%# form.submit class: "ml-2 fill-marche_white" do %>
這裡submit應該不能用了吧～直接刪除吧！

2023-05-06 15:28 UTC, Hsuan19971005 commented on app/models/product.rb
> +  def self.ransackable_attributes(auth_object = nil)
類別方法，只提供給Product這個類別使用，其他的實體變數無法使用
這邊的ransackable_attributes是允許ransack可以搜尋哪幾個資料表的欄位

2023-05-06 15:29 UTC, Hsuan19971005 commented on app/controllers/products_controller.rb
> +    @q = Product.ransack(params[:q])
這邊的@q是ransack的官方範例用法，之後是可以考慮換一下

2023-05-06 16:04 UTC, charlie51417 approved these changes

2023-05-06 16:04 UTC, merged