商品展示頁面 新增規格資訊變化
5xRuby13thMarche/Marche pull request #77
Opened 2023-05-05 09:43 UTC by charlie51417

#14 
如影片可以點選規格改變商品資訊

https://user-images.githubusercontent.com/127653623/236425478-66b61f9a-5cca-419a-a003-3877f97117f5.mov

進階說明：
藉由點選link去傳送一段網址夾帶id，取得網址內的id去判斷是哪一個sale_info
而去展示該id之資訊

2023-05-05 17:13 UTC, Hsuan19971005 requested changes
commit訊息可以改成：
feat: Add spec button feature in product show page

2023-05-05 17:13 UTC, hsiaoyihsuan commented on app/controllers/products_controller.rb
> +    @spec_all = SaleInfo.where(product_id: @product.id)
這邊我會比較習慣從@product去撈取，語法上比較直觀

2023-05-05 17:13 UTC, hsiaoyihsuan commented on app/controllers/products_controller.rb
註解寫得不錯，排版也很整齊

2023-05-05 17:13 UTC, Hsuan19971005 commented on app/views/products/_spec.html.erb
這個檔案名稱有點不太精準，因為還包含了不止規格的資訊，應該可以改名：「_product_info」or「_info」

2023-05-05 17:13 UTC, Hsuan19971005 commented on app/views/products/_spec.html.erb
> +    <% @spec_all.each do |s| %>
這邊應該可以改寫成partial render的形式，主要是程式碼比較簡潔

2023-05-05 17:13 UTC, Hsuan19971005 commented on app/views/products/_spec.html.erb
> +      <div class="flex mb-10">
這個div應該可以拔掉，用外面那一個div就好

2023-05-05 17:13 UTC, Hsuan19971005 commented on app/views/products/_spec.html.erb
> +  <%# 數量框 %>
這個數量框在編輯器上已經變成波動拳的樣子了，試著簡化一下html的層數

2023-05-07 06:07 UTC, kg936512 approved these changes

2023-05-07 06:23 UTC, Hsuan19971005 approved these changes

2023-05-07 06:24 UTC, matsuyama2000 approved these changes

2023-05-07 06:24 UTC, merged