更新登入頁面切版
5xRuby13thMarche/Marche pull request #78
Opened 2023-05-05 09:48 UTC by sharondolly

![screencapture-localhost-3000-users-sign-in-2023-05-05-17_36_27](https://user-images.githubusercontent.com/130358340/236426888-a8cc2d3b-4bfb-4419-86a3-fdca6b422de7.png)

![screencapture-localhost-3000-users-sign-in-2023-05-05-17_36_39](https://user-images.githubusercontent.com/130358340/236426905-f1b1709a-7eef-4226-80cc-fef65c02f380.png)

2023-05-05 17:20 UTC, Hsuan19971005 requested changes
建議裝上headwind這個vscode的extension
commit訊息中的Update拼錯字了

2023-05-05 17:20 UTC, Hsuan19971005 commented on app/views/devise/sessions/new.html.erb
> +        <div class="field mb-3">
這邊開始的縮排沒有縮好

2023-05-05 17:20 UTC, Hsuan19971005 commented on app/views/devise/sessions/new.html.erb
> +  <%# 輸入框 %>
有加上註解很不錯，這樣程式碼很好閱讀

2023-05-06 12:21 UTC, charlie51417 approved these changes

2023-05-07 04:02 UTC, closed without merging